# Generated by Django 3.2.8 on 2021-10-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20211024_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='lookingforpeople',
            field=models.BooleanField(default=True),
        ),
    ]
